site_name: Sim Racing on Linux Wiki
site_url: https://wiki.simracingonlinux.com
theme:
  name: shadcn
markdown_extensions:
  - admonition
  - codehilite
  - fenced_code
  - pymdownx.highlight:
      css_class: codehilite
  - pymdownx.superfences
plugins:
  - search
  - awesome-nav
