[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.yaml", "*.yml"]

[formatter.markdownlint]
command = "markdownlint"
options = ["--fix", "--config", ".markdownlint.json"]
includes = ["*.md"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
